### ISSUE TITLE
Get number on amount of mentions on each tweet.

### ISSUE THREAD

**Issue by RiskyRusky** [zackotterstrom/SAoT#17]
we need this function for the search in "/tweets" have no clue how to count the amount of mentions per tweet.

**Comment by itggot-linus-styren** [comment]
You can use `tweet.mentions.length` to get the number of tweets.

**Comment by itggot-linus-styren** [comment]
@RiskyRusky Consider opening a pull request so we can merge this code when completed.

**Comment by itggot-linus-styren** [comment]
This was resolved in #21
